package cst4;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CFG extends JFrame {
    /**
     * Creates new form CFG
     */
    public CFG() {
        initComponents();

    btnClear.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            clearTextAreas();
        }
    });

    btnInput.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            inputStringAction();
        }
    });
    
    txtArea.setText("Production Rule:\nS → aSa\nS → bSb\nS → c\n");
    
    
    getContentPane().setBackground(new Color(0, 0, 51));
    
    }
    
    private void clearTextAreas() {
    txtArea.setText("Production Rule:\nS → aSa\nS → bSb\nS → c\n");
    txtArea3.setText("");
    txtArea2.setText("");
    txtField.setText("");
}

// Handle input when button3 (INPUT) is pressed
private void inputStringAction() {
    String input = txtField.getText().trim();
    if (input.isEmpty()) {
        txtArea3.setText("Please enter a string.");
        return;
    }
        if (isAccepted(input)) {
            txtArea2.setText("Accepted: " + input + "\n");
            txtArea2.append("Transformed: " + transformString(input) + "\n");
            txtArea3.setText("Derivation Steps:\n");
            showDerivationSteps(input);
        } else {
            txtArea2.setText("Rejected: " + input + "\nReason: The string is not valid or not a palindrome.");
        }
    }

public void showDerivationSteps(String str) {
        String current = "S";
        txtArea3.append(current + "\n");

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch == 'a' || ch == 'b') {
                String newDerivation = ch + "S" + ch;
                current = current.replaceFirst("S", newDerivation);
            } else if (ch == 'c') {
                current = current.replaceFirst("S", "c");
            }
            txtArea3.append(current + "\n");
        }
    }

public boolean isAccepted(String str) {
        return isValidCharacters(str) && isPalindrome(str);
    }

    // Validate characters (must be 'a', 'b', or 'c')
    private boolean isValidCharacters(String str) {
        for (char ch : str.toCharArray()) {
            if (ch != 'a' && ch != 'b' && ch != 'c') {
                return false;
            }
        }
        return true;
    }
    
private boolean isPalindrome(String str) {
        int left = 0;
        int right = str.length() - 1;
        while (left < right) {
            if (str.charAt(left) != str.charAt(right)) {
                return false;
            }
            left++;
            right--;
        }
        return true;
    }

private String transformString(String input) {
        return input + "c" + new StringBuilder(input).reverse().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea3 = new javax.swing.JTextArea();
        txtField = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Context Free Grammar");
        setBackground(new java.awt.Color(0, 0, 51));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea3.setEditable(false);
        txtArea3.setBackground(new java.awt.Color(0, 0, 0));
        txtArea3.setColumns(20);
        txtArea3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea3.setForeground(new java.awt.Color(51, 255, 51));
        txtArea3.setRows(5);
        jScrollPane1.setViewportView(txtArea3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 390, 250));

        txtField.setBackground(new java.awt.Color(0, 0, 0));
        txtField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtField.setForeground(new java.awt.Color(51, 255, 51));
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 270, 70));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 0, 0));
        btnClear.setText("CLEAR");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 180, 50));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 0));
        btnBack.setText("BACK TO MAIN MENU");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 180, 50));

        btnInput.setBackground(new java.awt.Color(0, 0, 0));
        btnInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInput.setForeground(new java.awt.Color(0, 255, 0));
        btnInput.setText("INPUT");
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 180, 50));

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(0, 0, 0));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea.setForeground(new java.awt.Color(51, 255, 51));
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 350, 250));

        txtArea2.setEditable(false);
        txtArea2.setBackground(new java.awt.Color(0, 0, 0));
        txtArea2.setColumns(20);
        txtArea2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea2.setForeground(new java.awt.Color(51, 255, 51));
        txtArea2.setRows(5);
        jScrollPane3.setViewportView(txtArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 350, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MACHINE machineFrame = new MACHINE();
        machineFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CFG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CFG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CFG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CFG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CFG().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtArea2;
    private javax.swing.JTextArea txtArea3;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
