/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import java.util.List;
/**
 *
 * @author jppisonet
 */
public class NFA extends javax.swing.JFrame {
    private Map<String, Map<String, List<String>>> stateTable;
    private String currentState;
    private List<String> acceptingStates;
    private Random random;
    /**
     * Creates new form NFA
     */
    public NFA() {
        initComponents();
        setSize(1200, 700);
        pack();
        
        getContentPane().setBackground(Color.CYAN);

        stateTable = new HashMap<>();
        acceptingStates = new ArrayList<>();
        random = new Random();

        stateTable.put("A", new HashMap<>());
        stateTable.get("A").put("a", Arrays.asList("B", "E"));
        stateTable.get("A").put("b", Collections.emptyList());
        stateTable.get("A").put("c", Collections.emptyList());

        stateTable.put("B", new HashMap<>());
        stateTable.get("B").put("a", Collections.emptyList());
        stateTable.get("B").put("b", Arrays.asList("C"));
        stateTable.get("B").put("c", Collections.emptyList());

        stateTable.put("C", new HashMap<>());
        stateTable.get("C").put("a", Collections.emptyList());
        stateTable.get("C").put("b", Collections.emptyList());
        stateTable.get("C").put("c", Arrays.asList("D"));

        stateTable.put("D", new HashMap<>());
        stateTable.get("D").put("a", Collections.emptyList());
        stateTable.get("D").put("b", Collections.emptyList());
        stateTable.get("D").put("c", Collections.emptyList());

        stateTable.put("E", new HashMap<>());
        stateTable.get("E").put("a", Collections.emptyList());
        stateTable.get("E").put("b", Arrays.asList("F"));
        stateTable.get("E").put("c", Collections.emptyList());

        stateTable.put("F", new HashMap<>());
        stateTable.get("F").put("a", Collections.emptyList());
        stateTable.get("F").put("b", Collections.emptyList());
        stateTable.get("F").put("c", Arrays.asList("E"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea2 = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Non-Deterministic Finite Automata");
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("(without epsilon)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Non-Deterministic Finite Automata");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Input String:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 190, 70));

        btnEnter.setBackground(new java.awt.Color(0, 153, 153));
        btnEnter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 250, 120, 70));
        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 540, 360));

        txtArea2.setColumns(20);
        txtArea2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtArea2.setRows(5);
        jScrollPane3.setViewportView(txtArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 134, 410, 86));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 250, 120, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 390, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("(Only accepts alphabet a, b, and c)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MACHINE machineFrame = new MACHINE();
        machineFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        currentState = "A";
        acceptingStates = Arrays.asList("D", "F");

        String inputString = txtArea2.getText();

        JTextArea outputArea = new JTextArea();
        outputArea.setEditable(false);

        for (char symbol : inputString.toCharArray()) {
            String nextState = transition(String.valueOf(symbol));
            outputArea.append("\nCurrent Input: " + symbol + "\nState: " + nextState + "\n");
            if (nextState == null) {
                outputArea.append(" ");
                break;
            }
        }

        if (isAcceptingState()) {
            outputArea.append("\nSTRING ACCEPTED\n");
        } else {
            outputArea.append("\nSTRING REJECTED\n");
        }

        scrollPane.setViewportView(outputArea);
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtArea2.setText("");
        JTextArea textAreaInScrollPane = (JTextArea) scrollPane.getViewport().getView();
        textAreaInScrollPane.setText("");
    }//GEN-LAST:event_btnClearActionPerformed
        public String transition(String inputSymbol) {
        List<String> nextStates = stateTable.get(currentState).get(inputSymbol);
        if (nextStates == null || nextStates.isEmpty()) {
            return null;
        }

        int nextStateIndex = random.nextInt(nextStates.size());
        currentState = nextStates.get(nextStateIndex);
        return currentState;
    }

    public boolean isAcceptingState() {
        return acceptingStates.contains(currentState);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NFA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtArea2;
    // End of variables declaration//GEN-END:variables
}
