/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class MACHINE extends javax.swing.JFrame {

    /**
     * Creates new form MACHINE
     */
    public MACHINE() {
        initComponents();
        
        setupButtonHoverEffect(btnDFA);
        setupButtonHoverEffect(btnNFA);
        setupButtonHoverEffect(btnCFG);
        setupButtonHoverEffect(btnTM);
        setupButtonHoverEffect(btnPDA);
        setupButtonHoverEffect(btnTOH);
        
            addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame) e.getSource();

                // Show confirmation dialog
                int result = JOptionPane.showConfirmDialog(
                        frame,
                        "Are you sure you want to close the window?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                // If user clicks 'Yes', close the window; otherwise, do nothing
                if (result == JOptionPane.YES_OPTION) {
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Prevent the window from closing
                }
            }
        });
    }
    
    @Override
public void paint(Graphics g) {
    super.paint(g);
    getContentPane().setBackground(Color.LIGHT_GRAY);
}

    
    private void setupButtonHoverEffect(javax.swing.JButton button) {
    button.setBorderPainted(false);    // Remove border
    button.setContentAreaFilled(false); // Make background transparent
    button.setFocusPainted(false);      // Remove focus outline
    
    button.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent evt) {
            button.setContentAreaFilled(true); // Make button fill when hovered
            button.setBackground(Color.LIGHT_GRAY); // Change to light gray when hovered
        }
        @Override
        public void mouseExited(MouseEvent evt) {
            button.setContentAreaFilled(false); // Revert to transparent when not hovered
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDFA = new javax.swing.JButton();
        btnNFA = new javax.swing.JButton();
        btnCFG = new javax.swing.JButton();
        btnTM = new javax.swing.JButton();
        btnPDA = new javax.swing.JButton();
        btnTOH = new javax.swing.JButton();
        kakashiJPG = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTOMATA HUB");
        setBackground(new java.awt.Color(51, 102, 0));
        setFocusable(false);
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("MACHINE VAULT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 330, 80));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 123, 700, 30));

        btnDFA.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        btnDFA.setText("Deterministic Finite Automata");
        btnDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFAActionPerformed(evt);
            }
        });
        getContentPane().add(btnDFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 640, 60));

        btnNFA.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        btnNFA.setText("Non Deterministic Finite AUtomata");
        btnNFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNFAActionPerformed(evt);
            }
        });
        getContentPane().add(btnNFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 640, 60));

        btnCFG.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        btnCFG.setText("Context Free Grammar");
        btnCFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFGActionPerformed(evt);
            }
        });
        getContentPane().add(btnCFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 640, 60));

        btnTM.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        btnTM.setText("Turing Machine");
        btnTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTMActionPerformed(evt);
            }
        });
        getContentPane().add(btnTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 640, 60));

        btnPDA.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        btnPDA.setText("Push Down Automata");
        btnPDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDAActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 640, 60));

        btnTOH.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        btnTOH.setText("Tower of Hanoi");
        btnTOH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOHActionPerformed(evt);
            }
        });
        getContentPane().add(btnTOH, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 640, 60));

        kakashiJPG.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\banPNG-removeBG.png")); // NOI18N
        getContentPane().add(kakashiJPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 370, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\peppa-removedBG.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 250, 380));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\deathnote-removedBG.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 320, 420));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\kapNoBG.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 470, 190, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\guoNoBG.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 200, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDAActionPerformed
        PDA pdaFrame = new PDA();
        pdaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPDAActionPerformed

    private void btnDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFAActionPerformed
        DFA dfaFrame = new DFA();
        dfaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDFAActionPerformed

    private void btnTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTMActionPerformed
        TuringMachine tmFrame = new TuringMachine();
        tmFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTMActionPerformed

    private void btnTOHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOHActionPerformed
        TOH tohFrame = new TOH();
        tohFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTOHActionPerformed

    private void btnCFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFGActionPerformed
        CFG cfgFrame = new CFG();
        cfgFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCFGActionPerformed

    private void btnNFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNFAActionPerformed
        NFA nfaFrame = new NFA();
        nfaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNFAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MACHINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MACHINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MACHINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MACHINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MACHINE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCFG;
    private javax.swing.JButton btnDFA;
    private javax.swing.JButton btnNFA;
    private javax.swing.JButton btnPDA;
    private javax.swing.JButton btnTM;
    private javax.swing.JButton btnTOH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kakashiJPG;
    // End of variables declaration//GEN-END:variables
}
